Fix exception on unnexpected warning format
This should fix the following exception caused by an unexpectly formated line in the doxygen warnings:

FileNotFoundError: [Errno 2] No such file or directory: '\n'